const kinds = @import("browser_kind.zig");

pub const BrowserKind = kinds.BrowserKind;
pub const EngineKind = kinds.EngineKind;
pub const Platform = kinds.Platform;

pub const BrowserPathHints = struct {
    kind: BrowserKind,
    engine: EngineKind,
    platform: Platform,
    executable_names: []const []const u8,
    known_paths: []const []const u8,
    mac_bundle_ids: []const []const u8,
    windows_registry_hints: []const []const u8,
    linux_package_hints: []const []const u8,
    confidence_weight: i32,
};

pub const all_browser_kinds = [_]BrowserKind{
    .chrome,
    .edge,
    .safari,
    .firefox,
    .brave,
    .tor,
    .duckduckgo,
    .mullvad,
    .librewolf,
    .epic,
    .arc,
    .vivaldi,
    .sigmaos,
    .sidekick,
    .shift,
    .operagx,
    .palemoon,
};

pub fn hintsFor(kind: BrowserKind, platform: Platform) BrowserPathHints {
    return switch (platform) {
        .windows => windowsHints(kind),
        .macos => macHints(kind),
        .linux => linuxHints(kind),
    };
}

fn windowsHints(kind: BrowserKind) BrowserPathHints {
    return switch (kind) {
        .chrome => .{
            .kind = .chrome,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "chrome", "chrome.exe" },
            .known_paths = &.{
                "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
                "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{
                "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\chrome.exe",
                "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\chrome.exe",
            },
            .linux_package_hints = &.{},
            .confidence_weight = 100,
        },
        .edge => .{
            .kind = .edge,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "msedge", "msedge.exe" },
            .known_paths = &.{
                "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe",
                "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{ "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\msedge.exe" },
            .linux_package_hints = &.{},
            .confidence_weight = 100,
        },
        .safari => .{
            .kind = .safari,
            .engine = .webkit,
            .platform = .windows,
            .executable_names = &.{},
            .known_paths = &.{},
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 0,
        },
        .firefox => .{
            .kind = .firefox,
            .engine = .gecko,
            .platform = .windows,
            .executable_names = &.{ "firefox", "firefox.exe" },
            .known_paths = &.{
                "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
                "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{ "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\firefox.exe" },
            .linux_package_hints = &.{},
            .confidence_weight = 100,
        },
        .brave => .{
            .kind = .brave,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "brave", "brave.exe", "brave-browser", "brave-browser.exe" },
            .known_paths = &.{
                "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
                "C:\\Program Files (x86)\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{ "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\brave.exe" },
            .linux_package_hints = &.{},
            .confidence_weight = 90,
        },
        .tor => .{
            .kind = .tor,
            .engine = .gecko,
            .platform = .windows,
            .executable_names = &.{ "tor-browser", "firefox.exe" },
            .known_paths = &.{
                "C:\\Program Files\\Tor Browser\\Browser\\firefox.exe",
                "C:\\Users\\%USERNAME%\\Desktop\\Tor Browser\\Browser\\firefox.exe",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 70,
        },
        .duckduckgo => .{
            .kind = .duckduckgo,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "duckduckgo", "duckduckgo.exe", "duckduckgo-browser.exe" },
            .known_paths = &.{ "C:\\Program Files\\DuckDuckGo\\DuckDuckGo.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 60,
        },
        .mullvad => .{
            .kind = .mullvad,
            .engine = .gecko,
            .platform = .windows,
            .executable_names = &.{ "mullvad-browser", "mullvadbrowser", "firefox.exe" },
            .known_paths = &.{ "C:\\Program Files\\Mullvad Browser\\firefox.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 70,
        },
        .librewolf => .{
            .kind = .librewolf,
            .engine = .gecko,
            .platform = .windows,
            .executable_names = &.{ "librewolf", "librewolf.exe" },
            .known_paths = &.{ "C:\\Program Files\\LibreWolf\\librewolf.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 70,
        },
        .epic => .{
            .kind = .epic,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "epic", "epic.exe", "epicbrowser.exe" },
            .known_paths = &.{ "C:\\Program Files\\Epic Privacy Browser\\epic.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 65,
        },
        .arc => .{
            .kind = .arc,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "arc", "arc.exe" },
            .known_paths = &.{ "C:\\Program Files\\Arc\\Arc.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 60,
        },
        .vivaldi => .{
            .kind = .vivaldi,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "vivaldi", "vivaldi.exe" },
            .known_paths = &.{
                "C:\\Program Files\\Vivaldi\\Application\\vivaldi.exe",
                "C:\\Program Files (x86)\\Vivaldi\\Application\\vivaldi.exe",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{ "HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\vivaldi.exe" },
            .linux_package_hints = &.{},
            .confidence_weight = 90,
        },
        .sigmaos => .{
            .kind = .sigmaos,
            .engine = .unknown,
            .platform = .windows,
            .executable_names = &.{},
            .known_paths = &.{},
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 0,
        },
        .sidekick => .{
            .kind = .sidekick,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "sidekick", "sidekick.exe" },
            .known_paths = &.{ "C:\\Program Files\\Sidekick\\sidekick.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 65,
        },
        .shift => .{
            .kind = .shift,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "shift", "shift.exe" },
            .known_paths = &.{ "C:\\Program Files\\Shift\\Shift.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 65,
        },
        .operagx => .{
            .kind = .operagx,
            .engine = .chromium,
            .platform = .windows,
            .executable_names = &.{ "opera", "opera.exe", "launcher.exe" },
            .known_paths = &.{ "C:\\Users\\%USERNAME%\\AppData\\Local\\Programs\\Opera GX\\launcher.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{ "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\App Paths\\launcher.exe" },
            .linux_package_hints = &.{},
            .confidence_weight = 60,
        },
        .palemoon => .{
            .kind = .palemoon,
            .engine = .gecko,
            .platform = .windows,
            .executable_names = &.{ "palemoon", "palemoon.exe" },
            .known_paths = &.{ "C:\\Program Files\\Pale Moon\\palemoon.exe" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 50,
        },
    };
}

fn macHints(kind: BrowserKind) BrowserPathHints {
    return switch (kind) {
        .chrome => .{
            .kind = .chrome,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Google Chrome" },
            .known_paths = &.{
                "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
                "/Applications/Google Chrome Beta.app/Contents/MacOS/Google Chrome Beta",
            },
            .mac_bundle_ids = &.{ "com.google.Chrome", "com.google.Chrome.beta" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 100,
        },
        .edge => .{
            .kind = .edge,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Microsoft Edge" },
            .known_paths = &.{
                "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
                "/Applications/Microsoft Edge Beta.app/Contents/MacOS/Microsoft Edge Beta",
            },
            .mac_bundle_ids = &.{ "com.microsoft.edgemac", "com.microsoft.edgemac.Beta" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 100,
        },
        .safari => .{
            .kind = .safari,
            .engine = .webkit,
            .platform = .macos,
            .executable_names = &.{ "Safari", "safaridriver" },
            .known_paths = &.{
                "/Applications/Safari.app/Contents/MacOS/Safari",
                "/System/Applications/Safari.app/Contents/MacOS/Safari",
                "/usr/bin/safaridriver",
            },
            .mac_bundle_ids = &.{ "com.apple.Safari" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 110,
        },
        .firefox => .{
            .kind = .firefox,
            .engine = .gecko,
            .platform = .macos,
            .executable_names = &.{ "Firefox" },
            .known_paths = &.{ "/Applications/Firefox.app/Contents/MacOS/firefox" },
            .mac_bundle_ids = &.{ "org.mozilla.firefox" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 100,
        },
        .brave => .{
            .kind = .brave,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Brave Browser" },
            .known_paths = &.{ "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" },
            .mac_bundle_ids = &.{ "com.brave.Browser" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 90,
        },
        .tor => .{
            .kind = .tor,
            .engine = .gecko,
            .platform = .macos,
            .executable_names = &.{ "Tor Browser" },
            .known_paths = &.{ "/Applications/Tor Browser.app/Contents/MacOS/firefox" },
            .mac_bundle_ids = &.{ "org.torproject.torbrowser" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 70,
        },
        .duckduckgo => .{
            .kind = .duckduckgo,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "DuckDuckGo" },
            .known_paths = &.{ "/Applications/DuckDuckGo.app/Contents/MacOS/DuckDuckGo" },
            .mac_bundle_ids = &.{ "com.duckduckgo.macos.browser" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 60,
        },
        .mullvad => .{
            .kind = .mullvad,
            .engine = .gecko,
            .platform = .macos,
            .executable_names = &.{ "Mullvad Browser" },
            .known_paths = &.{ "/Applications/Mullvad Browser.app/Contents/MacOS/firefox" },
            .mac_bundle_ids = &.{ "net.mullvad.MullvadBrowser" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 70,
        },
        .librewolf => .{
            .kind = .librewolf,
            .engine = .gecko,
            .platform = .macos,
            .executable_names = &.{ "LibreWolf" },
            .known_paths = &.{ "/Applications/LibreWolf.app/Contents/MacOS/librewolf" },
            .mac_bundle_ids = &.{ "io.gitlab.librewolf-community" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 70,
        },
        .epic => .{
            .kind = .epic,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Epic" },
            .known_paths = &.{ "/Applications/Epic.app/Contents/MacOS/Epic" },
            .mac_bundle_ids = &.{ "com.hiddenreflex.epic" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 65,
        },
        .arc => .{
            .kind = .arc,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Arc" },
            .known_paths = &.{ "/Applications/Arc.app/Contents/MacOS/Arc" },
            .mac_bundle_ids = &.{ "company.thebrowser.Browser" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 90,
        },
        .vivaldi => .{
            .kind = .vivaldi,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Vivaldi" },
            .known_paths = &.{ "/Applications/Vivaldi.app/Contents/MacOS/Vivaldi" },
            .mac_bundle_ids = &.{ "com.vivaldi.Vivaldi" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 90,
        },
        .sigmaos => .{
            .kind = .sigmaos,
            .engine = .unknown,
            .platform = .macos,
            .executable_names = &.{ "SigmaOS" },
            .known_paths = &.{ "/Applications/SigmaOS.app/Contents/MacOS/SigmaOS" },
            .mac_bundle_ids = &.{ "com.sigmaos.sigmaos" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 60,
        },
        .sidekick => .{
            .kind = .sidekick,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Sidekick" },
            .known_paths = &.{ "/Applications/Sidekick.app/Contents/MacOS/Sidekick" },
            .mac_bundle_ids = &.{ "com.pushplaylabs.sidekick" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 65,
        },
        .shift => .{
            .kind = .shift,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Shift" },
            .known_paths = &.{ "/Applications/Shift.app/Contents/MacOS/Shift" },
            .mac_bundle_ids = &.{ "com.tryshift.shift" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 65,
        },
        .operagx => .{
            .kind = .operagx,
            .engine = .chromium,
            .platform = .macos,
            .executable_names = &.{ "Opera GX" },
            .known_paths = &.{ "/Applications/Opera GX.app/Contents/MacOS/Opera GX" },
            .mac_bundle_ids = &.{ "com.operasoftware.OperaGX" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 60,
        },
        .palemoon => .{
            .kind = .palemoon,
            .engine = .gecko,
            .platform = .macos,
            .executable_names = &.{ "Pale Moon" },
            .known_paths = &.{ "/Applications/Pale Moon.app/Contents/MacOS/palemoon" },
            .mac_bundle_ids = &.{ "org.palemoon.browser" },
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 45,
        },
    };
}

fn linuxHints(kind: BrowserKind) BrowserPathHints {
    return switch (kind) {
        .chrome => .{
            .kind = .chrome,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "google-chrome", "google-chrome-stable", "chrome" },
            .known_paths = &.{
                "/usr/bin/google-chrome",
                "/usr/bin/google-chrome-stable",
                "/opt/google/chrome/chrome",
                "/snap/bin/chromium",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "google-chrome-stable", "google-chrome" },
            .confidence_weight = 100,
        },
        .edge => .{
            .kind = .edge,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "microsoft-edge", "microsoft-edge-stable", "msedge" },
            .known_paths = &.{
                "/usr/bin/microsoft-edge",
                "/usr/bin/microsoft-edge-stable",
                "/usr/bin/microsoft-edge-beta",
                "/usr/bin/microsoft-edge-dev",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "microsoft-edge-stable", "microsoft-edge" },
            .confidence_weight = 95,
        },
        .safari => .{
            .kind = .safari,
            .engine = .webkit,
            .platform = .linux,
            .executable_names = &.{},
            .known_paths = &.{},
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 0,
        },
        .firefox => .{
            .kind = .firefox,
            .engine = .gecko,
            .platform = .linux,
            .executable_names = &.{ "firefox" },
            .known_paths = &.{
                "/usr/bin/firefox",
                "/snap/bin/firefox",
                "/opt/firefox/firefox",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "firefox" },
            .confidence_weight = 100,
        },
        .brave => .{
            .kind = .brave,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "brave-browser", "brave" },
            .known_paths = &.{
                "/usr/bin/brave-browser",
                "/opt/brave.com/brave/brave-browser",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "brave-browser" },
            .confidence_weight = 90,
        },
        .tor => .{
            .kind = .tor,
            .engine = .gecko,
            .platform = .linux,
            .executable_names = &.{ "tor-browser", "torbrowser-launcher" },
            .known_paths = &.{
                "/usr/bin/tor-browser",
                "/usr/bin/torbrowser-launcher",
                "/opt/tor-browser/Browser/firefox",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "torbrowser-launcher", "tor-browser" },
            .confidence_weight = 70,
        },
        .duckduckgo => .{
            .kind = .duckduckgo,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "duckduckgo-browser", "duckduckgo" },
            .known_paths = &.{ "/usr/bin/duckduckgo-browser" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "duckduckgo-browser" },
            .confidence_weight = 40,
        },
        .mullvad => .{
            .kind = .mullvad,
            .engine = .gecko,
            .platform = .linux,
            .executable_names = &.{ "mullvad-browser", "mullvadbrowser" },
            .known_paths = &.{
                "/usr/bin/mullvad-browser",
                "/opt/mullvad-browser/firefox",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "mullvad-browser" },
            .confidence_weight = 70,
        },
        .librewolf => .{
            .kind = .librewolf,
            .engine = .gecko,
            .platform = .linux,
            .executable_names = &.{ "librewolf" },
            .known_paths = &.{ "/usr/bin/librewolf" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "librewolf" },
            .confidence_weight = 70,
        },
        .epic => .{
            .kind = .epic,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "epic" },
            .known_paths = &.{ "/usr/bin/epic" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "epic-browser" },
            .confidence_weight = 35,
        },
        .arc => .{
            .kind = .arc,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "arc" },
            .known_paths = &.{ "/usr/bin/arc" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "arc-browser" },
            .confidence_weight = 30,
        },
        .vivaldi => .{
            .kind = .vivaldi,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "vivaldi", "vivaldi-stable", "vivaldi-snapshot" },
            .known_paths = &.{
                "/usr/bin/vivaldi",
                "/usr/bin/vivaldi-stable",
                "/opt/vivaldi/vivaldi",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "vivaldi-stable", "vivaldi" },
            .confidence_weight = 90,
        },
        .sigmaos => .{
            .kind = .sigmaos,
            .engine = .unknown,
            .platform = .linux,
            .executable_names = &.{},
            .known_paths = &.{},
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{},
            .confidence_weight = 0,
        },
        .sidekick => .{
            .kind = .sidekick,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "sidekick", "sidekick-browser" },
            .known_paths = &.{ "/usr/bin/sidekick-browser" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "sidekick-browser" },
            .confidence_weight = 65,
        },
        .shift => .{
            .kind = .shift,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "shift", "shift-browser" },
            .known_paths = &.{ "/usr/bin/shift-browser" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "shift-browser" },
            .confidence_weight = 45,
        },
        .operagx => .{
            .kind = .operagx,
            .engine = .chromium,
            .platform = .linux,
            .executable_names = &.{ "opera", "opera-gx" },
            .known_paths = &.{
                "/usr/bin/opera",
                "/usr/bin/opera-gx",
                "/snap/bin/opera",
            },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "opera-stable", "opera" },
            .confidence_weight = 55,
        },
        .palemoon => .{
            .kind = .palemoon,
            .engine = .gecko,
            .platform = .linux,
            .executable_names = &.{ "palemoon" },
            .known_paths = &.{ "/usr/bin/palemoon" },
            .mac_bundle_ids = &.{},
            .windows_registry_hints = &.{},
            .linux_package_hints = &.{ "palemoon" },
            .confidence_weight = 50,
        },
    };
}
